name: Deploy with Ansible

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible
      run: sudo apt update && sudo apt install ansible -y

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible_key
        chmod 600 ansible_key

    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory.ini playbook.yml --private-key ansible_key
